import { Montserrat, Open_Sans } from "next/font/google";
import "./../styles/main.scss";

const montserrat = Montserrat({
	variable: "--font-title",
	subsets: ["latin"],
});

const open_Sans = Open_Sans({
	variable: "--font-main",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${montserrat.variable} ${open_Sans.variable}`}>
				{children}
			</body>
		</html>
	);
}
